### ISSUE TITLE
Add ability to switch between gold and TC prices

### ISSUE THREAD

**Issue by Marilyth** [Marilyth/tibia-market-tracker-website#10]

**Comment by fenesco** [comment]
This doesn't make much sense, for the following reasons:

1. The game does not have a native TC/GP conversion in the Market itself
2. If the servant used the average price of the TC and converted it manually, he would have to take into account the average price of each day

**Comment by Marilyth** [comment]
@fenesco I don't see the problem then, we have the average price of TC for each day available. I imagine this to be an easy to implement feature.
